server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server8761

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server8762:8762/eureka/,http://eureka-server8763:8763/eureka/

#  server:
#自我保护机制
#    enable-self-preservation: false



